# Generated by Django 4.1.7 on 2023-03-29 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tabledata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=20)),
                ('Age', models.IntegerField(default='', max_length=5)),
                ('Contact_number', models.IntegerField(default='', max_length=10)),
                ('Email', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
